#!/bin/bash

set -e

rm -rf libxcypt-*

URL=$(curl -s https://api.github.com/besser82/libxcrypt/releases/latest \
  | grep "browser_download_url" \
  | cut -d '"' -f 4 \
  | grep '\.tar\.gz$')

STAGE=$(basename "$URL" .tar.xz)
tar -xvf "$LATEST"

cd $STAGE

# 64 bit

./configure --prefix=/usr                \
            --enable-hashes=strong,glibc \
            --enable-obsolete-api=no     \
            --disable-static             \
            --disable-failure-tokens

$MAKE

$MAKE install

# 32 bit

make distclean

CC="gcc -m32" \
./configure --prefix=/usr                \
            --host=i686-pc-linux-gnu     \
            --libdir=/usr/lib32          \
            --enable-hashes=strong,glibc \
            --enable-obsolete-api=glibc  \
            --disable-static             \
            --disable-failure-tokens

$MAKE

cp -av .libs/libcrypt.so* $LFS/usr/lib32/ &&
make install-pkgconfigDATA &&
ln -svf libxcrypt.pc $LFS/usr/lib32/pkgconfig/libcrypt.pc


